# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PPTEB_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(350, 420, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_btn.sizePolicy().hasHeightForWidth())
        self.create_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.create_btn.setFont(font)
        self.create_btn.setObjectName("create_btn")
        self.close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(500, 420, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName("close_btn")
        self.min_max_desc = QtWidgets.QLabel(self.centralwidget)
        self.min_max_desc.setGeometry(QtCore.QRect(50, 280, 501, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_max_desc.sizePolicy().hasHeightForWidth())
        self.min_max_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.min_max_desc.setFont(font)
        self.min_max_desc.setObjectName("min_max_desc")
        self.min_slider = QtWidgets.QSlider(self.centralwidget)
        self.min_slider.setGeometry(QtCore.QRect(112, 310, 431, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_slider.sizePolicy().hasHeightForWidth())
        self.min_slider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.min_slider.setFont(font)
        self.min_slider.setMinimum(1)
        self.min_slider.setMaximum(20)
        self.min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_slider.setObjectName("min_slider")
        self.max_slider = QtWidgets.QSlider(self.centralwidget)
        self.max_slider.setGeometry(QtCore.QRect(112, 349, 431, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_slider.sizePolicy().hasHeightForWidth())
        self.max_slider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.max_slider.setFont(font)
        self.max_slider.setMinimum(1)
        self.max_slider.setMaximum(20)
        self.max_slider.setPageStep(1)
        self.max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.max_slider.setObjectName("max_slider")
        self.min_label = QtWidgets.QLabel(self.centralwidget)
        self.min_label.setGeometry(QtCore.QRect(50, 310, 52, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_label.sizePolicy().hasHeightForWidth())
        self.min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.min_label.setFont(font)
        self.min_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.min_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.min_label.setObjectName("min_label")
        self.max_label = QtWidgets.QLabel(self.centralwidget)
        self.max_label.setGeometry(QtCore.QRect(50, 350, 52, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_label.sizePolicy().hasHeightForWidth())
        self.max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.max_label.setFont(font)
        self.max_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_label.setObjectName("max_label")
        self.cb_label = QtWidgets.QLabel(self.centralwidget)
        self.cb_label.setGeometry(QtCore.QRect(43, 220, 151, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_label.sizePolicy().hasHeightForWidth())
        self.cb_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.cb_label.setFont(font)
        self.cb_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cb_label.setObjectName("cb_label")
        self.severity_cb = QtWidgets.QComboBox(self.centralwidget)
        self.severity_cb.setGeometry(QtCore.QRect(200, 160, 61, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.severity_cb.sizePolicy().hasHeightForWidth())
        self.severity_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.severity_cb.setFont(font)
        self.severity_cb.setMaxVisibleItems(5)
        self.severity_cb.setMaxCount(5)
        self.severity_cb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.severity_cb.setObjectName("severity_cb")
        self.severity_cb.addItem("")
        self.severity_cb.addItem("")
        self.severity_cb.addItem("")
        self.severity_cb.addItem("")
        self.severity_cb.addItem("")
        self.severity_label = QtWidgets.QLabel(self.centralwidget)
        self.severity_label.setGeometry(QtCore.QRect(53, 160, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.severity_label.sizePolicy().hasHeightForWidth())
        self.severity_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.severity_label.setFont(font)
        self.severity_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.severity_label.setObjectName("severity_label")
        self.ps_label = QtWidgets.QLabel(self.centralwidget)
        self.ps_label.setGeometry(QtCore.QRect(133, 110, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ps_label.sizePolicy().hasHeightForWidth())
        self.ps_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ps_label.setFont(font)
        self.ps_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ps_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ps_label.setObjectName("ps_label")
        self.cb_line = QtWidgets.QLineEdit(self.centralwidget)
        self.cb_line.setGeometry(QtCore.QRect(200, 220, 61, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_line.sizePolicy().hasHeightForWidth())
        self.cb_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.cb_line.setFont(font)
        self.cb_line.setObjectName("cb_line")
        self.pl_label = QtWidgets.QLabel(self.centralwidget)
        self.pl_label.setGeometry(QtCore.QRect(130, 50, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl_label.sizePolicy().hasHeightForWidth())
        self.pl_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pl_label.setFont(font)
        self.pl_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pl_label.setObjectName("pl_label")
        self.ps_slider = QtWidgets.QSlider(self.centralwidget)
        self.ps_slider.setGeometry(QtCore.QRect(200, 110, 341, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ps_slider.sizePolicy().hasHeightForWidth())
        self.ps_slider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ps_slider.setFont(font)
        self.ps_slider.setMinimum(1)
        self.ps_slider.setMaximum(10)
        self.ps_slider.setPageStep(1)
        self.ps_slider.setProperty("value", 4)
        self.ps_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ps_slider.setObjectName("ps_slider")
        self.pl_slider = QtWidgets.QSlider(self.centralwidget)
        self.pl_slider.setGeometry(QtCore.QRect(200, 50, 341, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl_slider.sizePolicy().hasHeightForWidth())
        self.pl_slider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pl_slider.setFont(font)
        self.pl_slider.setMinimum(1)
        self.pl_slider.setMaximum(20)
        self.pl_slider.setPageStep(1)
        self.pl_slider.setOrientation(QtCore.Qt.Horizontal)
        self.pl_slider.setObjectName("pl_slider")
        self.pl_slider_counter = QtWidgets.QLabel(self.centralwidget)
        self.pl_slider_counter.setGeometry(QtCore.QRect(550, 46, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl_slider_counter.sizePolicy().hasHeightForWidth())
        self.pl_slider_counter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pl_slider_counter.setFont(font)
        self.pl_slider_counter.setObjectName("pl_slider_counter")
        self.ps_slider_counter = QtWidgets.QLabel(self.centralwidget)
        self.ps_slider_counter.setGeometry(QtCore.QRect(550, 99, 20, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ps_slider_counter.sizePolicy().hasHeightForWidth())
        self.ps_slider_counter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ps_slider_counter.setFont(font)
        self.ps_slider_counter.setObjectName("ps_slider_counter")
        self.min_slider_counter = QtWidgets.QLabel(self.centralwidget)
        self.min_slider_counter.setGeometry(QtCore.QRect(550, 311, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_slider_counter.sizePolicy().hasHeightForWidth())
        self.min_slider_counter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.min_slider_counter.setFont(font)
        self.min_slider_counter.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.min_slider_counter.setObjectName("min_slider_counter")
        self.max_slider_counter = QtWidgets.QLabel(self.centralwidget)
        self.max_slider_counter.setGeometry(QtCore.QRect(550, 350, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_slider_counter.sizePolicy().hasHeightForWidth())
        self.max_slider_counter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.max_slider_counter.setFont(font)
        self.max_slider_counter.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.max_slider_counter.setObjectName("max_slider_counter")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.severity_cb.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pathfinder Playtest Encounter Builder"))
        self.create_btn.setText(_translate("MainWindow", "Create Encounters"))
        self.close_btn.setText(_translate("MainWindow", "Close"))
        self.min_max_desc.setText(_translate("MainWindow", "Select a minimum and maximum number of creatures to use in the encounter:"))
        self.min_label.setText(_translate("MainWindow", "Min"))
        self.max_label.setText(_translate("MainWindow", "Max"))
        self.cb_label.setText(_translate("MainWindow", "Manual XP Budget (Optional):"))
        self.severity_cb.setCurrentText(_translate("MainWindow", "Trivial"))
        self.severity_cb.setItemText(0, _translate("MainWindow", "Trivial"))
        self.severity_cb.setItemText(1, _translate("MainWindow", "Low"))
        self.severity_cb.setItemText(2, _translate("MainWindow", "High"))
        self.severity_cb.setItemText(3, _translate("MainWindow", "Severe"))
        self.severity_cb.setItemText(4, _translate("MainWindow", "Extreme"))
        self.severity_label.setText(_translate("MainWindow", "Encounter Severity:"))
        self.ps_label.setText(_translate("MainWindow", "Party Size:"))
        self.pl_label.setText(_translate("MainWindow", "Party Level:"))
        self.pl_slider_counter.setText(_translate("MainWindow", "1"))
        self.ps_slider_counter.setText(_translate("MainWindow", "4"))
        self.min_slider_counter.setText(_translate("MainWindow", "1"))
        self.max_slider_counter.setText(_translate("MainWindow", "1"))

